### ISSUE TITLE
인증 및 인가 리팩토링

### ISSUE THREAD

**Issue by KWAKMANBO** [boostcampwm-2024/web04-RealTicket#189]
### 인증 및 인가 리팩토링
- [ ] session 유지 시간 30분으로 변경
- [ ] session 정보 변경 시 key값에 user라는 prefix붙이기

### 특이사항
- 없음

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified session expiration time to 30 minutes and added 'user' prefix to Redis keys for session information.

You can review changes in this commit: https://github.com/lkilu6456546/boostcampwm-2024-web04-RealTicket-189/commit/d66c42e1c394ac9a3e9ff95f44280ed4848386f2.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
